apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-videojob"
  labels:
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  activeDeadlineSeconds: {{.Values.activeDeadlineSeconds}}
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - name: youtube-dl
        image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources:
          requests:
            memory: {{.Values.resources.requests.memory | quote}}
        command:
        - time 
        - -p 
        - youtube-dl
        args:
        - --output 
        - '%(title)s-%(id)s.%(ext)s'
        - --restrict-filenames
        - --format
        - bestvideo[ext!=webm]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]
        - --exec
        - ffmpeg -i {} -filter_complex "scale=iw*min(1920/iw\,1080/ih):ih*min(1920/iw\,1080/ih),pad=1920:1080:(1920-iw*min(1920/iw\,1080/ih))/2:(1080-ih*min(1920/iw\,1080/ih))/2" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 6000k -profile:v high -level 4.0 -preset veryslow -pix_fmt yuv420p -r 25/1 -c:a aac -ar 44100 -y -ac 2 -b:a 192k /mnt/converted/{}
        - {{ .Values.url }}
        volumeMounts:
        - mountPath: /mnt/converted
          name: nfs
      volumes:
      - name: nfs
        nfs:
          server: 10.132.0.4
          path: "/opt/converted"
      restartPolicy: {{.Values.restartPolicy}}
