apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-videojob"
  labels:
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  activeDeadlineSeconds: {{.Values.activeDeadlineSeconds}}
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - name: youtube-dl
        image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        command:
        - youtube-dl
        args:
        - --help
      - name: ffmpeg
        image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        command:
        - curl
        args:
        - icanhazip.com
      restartPolicy: {{.Values.restartPolicy}}
