apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-videojob"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - name: youtube-dl
        image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        command:
        - youtube-dl
        args:
        - --help
      - name: ffmpeg
        image: "{{.Values.image.repository}}/{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        command:
        - sh
        - -c
        args:
        - echo
        - shit
      restartPolicy: Never
